# permissions for end users to view snappasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: snappass-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: snappass-operator
    app.kubernetes.io/part-of: snappass-operator
    app.kubernetes.io/managed-by: kustomize
  name: snappass-viewer-role
rules:
- apiGroups:
  - snappass.doxmx.org
  resources:
  - snappasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snappass.doxmx.org
  resources:
  - snappasses/status
  verbs:
  - get
