apiVersion: snappass.doxmx.org/v1alpha1
kind: SnapPass
metadata:
  labels:
    app.kubernetes.io/name: snappass
    app.kubernetes.io/instance: snappass-sample
    app.kubernetes.io/part-of: snappass-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: snappass-operator
  name: snappass-sample
spec:
  redisSize: 2
  ## spec vars are translated into snake_case (unless snakeCaseParameters is set to false in watches.yml)
  ## This is one way to override the images used by the controller.
  ## Another way is to define these images in the deployment
  # redisImage: "registry.example.com/org/redis:latest"
  # redisPort: 1234
  # snappassImage: "registry.example.com/org/snappass:latest"
  # snappassPort: 4321
