apiVersion: snappass.doxmx.org/v1alpha1
kind: SnapPass
metadata:
  labels:
    app.kubernetes.io/name: snappass
    app.kubernetes.io/instance: snappass-sample
    app.kubernetes.io/part-of: snappass-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: snappass-operator
  name: snappass-sample
spec:
  # TODO(user): Add fields here
